# A config file for Supabase CLI.
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "vistrial"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 16

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://127.0.0.1:3000/auth/callback",
  "https://app.vistrial.io/auth/callback",
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_signup = false

[auth.email]
enable_signup = false
enable_confirmations = true
