// @ts-nocheck
// ============================================
// MORNING BRIEF GENERATOR
// Claude-powered daily operations brief
// ============================================

import { getSupabaseAdminClient } from '@/lib/supabase/admin';
import { sendSlackMessage } from '@/lib/slack/messages';

export async function generateMorningBrief(organizationId: string) {
  const admin = getSupabaseAdminClient();
  const todayStart = new Date(new Date().setHours(0, 0, 0, 0)).toISOString();

  const [{ data: notifications }, { data: clients }, { data: org }] = await Promise.all([
    admin.from('notifications').select('*').eq('organization_id', organizationId).gte('created_at', todayStart),
    admin.from('clients').select('company_name, health_score, health_trend, contract_end_date').eq('org_id', organizationId).neq('status', 'churned').order('health_score'),
    admin.from('organizations').select('slack_webhook_url').eq('id', organizationId).single(),
  ]);

  if (!clients) return;

  const total = clients.length;
  const healthy = clients.filter(c => (c.health_score || 50) >= 80).length;
  const watch = clients.filter(c => (c.health_score || 50) >= 60 && (c.health_score || 50) < 80).length;
  const atRisk = clients.filter(c => (c.health_score || 50) >= 40 && (c.health_score || 50) < 60).length;
  const critical = clients.filter(c => (c.health_score || 50) < 40).length;

  const alerted = (notifications || []).filter(n => n.urgency === 'critical' || n.urgency === 'urgent');
  const briefItems = (notifications || []).filter(n => n.urgency === 'important' || n.urgency === 'routine');

  let briefContent = `**Morning Brief — ${new Date().toLocaleDateString()}**\n\n`;
  briefContent += `${healthy} healthy | ${watch} watch | ${atRisk} at-risk | ${critical} critical (${total} total)\n\n`;

  if (alerted.length > 0) {
    briefContent += `**Already alerted today:**\n`;
    alerted.forEach(n => { briefContent += `• ${n.title}\n`; });
    briefContent += '\n';
  }

  if (briefItems.length > 0) {
    briefContent += `**Today's items:**\n`;
    briefItems.forEach(n => { briefContent += `• ${n.title}: ${n.message?.slice(0, 100)}\n`; });
    briefContent += '\n';
  }

  const needsAttention = clients.filter(c => (c.health_score || 50) < 60);
  if (needsAttention.length > 0) {
    briefContent += `**Needs attention:**\n`;
    needsAttention.slice(0, 5).forEach(c => { briefContent += `• ${c.company_name} — ${c.health_score}/100 (${c.health_trend || 'stable'})\n`; });
  }

  if (total > 0 && critical === 0 && atRisk === 0 && alerted.length === 0) {
    briefContent += `✅ All clients healthy. Nothing urgent today.\n`;
  }

  // Send to Slack
  if (org?.data?.slack_webhook_url) {
    await sendSlackMessage(org.data.slack_webhook_url, [
      { type: 'header', text: { type: 'plain_text', text: `☀️ Morning Brief — ${new Date().toLocaleDateString()}` } },
      { type: 'section', text: { type: 'mrkdwn', text: briefContent } },
      { type: 'context', elements: [{ type: 'mrkdwn', text: '_Generated by Vistrial Agent_' }] },
    ]);
  }

  // Store
  await admin.from('agent_actions_log').insert({ org_id: organizationId, action_type: 'morning_brief', action_detail: briefContent.slice(0, 500) });
}
